spring.application.name=my-agent-client
################ Log 相關設定 ################
logging.pattern.console=%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n
################ OpenAI 相關設定 ################
spring.ai.openai.api-key=${OPENAI_API_KEY}
################ SMTP 電子郵件 相關設定 ################
# docker-compose.yml 定義「Mailpit 怎麼跑」，application.properties 定義「Spring Boot 怎麼連到它」，兩邊要互相匹配才能通。
spring.mail.host=localhost
spring.mail.port=1025
# Mailpit 不需要驗證，所以設定為 false
spring.mail.properties.mail.smtp.auth=false
# Mailpit 不需要 TLS (Transport Layer Security)，所以設定為 false
spring.mail.properties.mail.smtp.starttls.enable=false
################ 自定義的 my-agent-client Inbox 相關設定 ################
# Agent 信箱基地站位址
my-agent-client.inbox.base-url=http://localhost:8025
# Agent 信箱地址（測試信的收件人）
my-agent-client.inbox.address=support@example.com
# 每隔幾毫秒輪詢一次收件匣（10000ms = 10 秒）
my-agent-client.inbox.poll-interval=10000
# 每次最多抓取幾封未讀郵件
my-agent-client.inbox.batch-size=50
################ MCP Client 相關設定 ################
# 設定一個叫做 mcp-server 的 streamable HTTP MCP server connection 去連線到一個已經存在的 MCP server：http://localhost:8090/mcp
spring.ai.mcp.client.streamable-http.connections.mcp-server.url=http://localhost:8090
spring.ai.mcp.client.streamable-http.connections.mcp-server.endpoint=/mcp